// Backpack.cpp
// This source file implements the functionality of the Backpack class.
// Also handles and emits all of the events generated by the backpack.
// The backpack includes and has access to its own:
// Inventory Class, TaskManager Class and eventGenerator Class.

#include "Backpack.h"
#include <iostream>
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Backpack constructor initializes the Backpack with a reference to an Inventory 
// object and initializes the TaskManager with the same Inventory reference.
Backpack::Backpack(Inventory& inventory)
    : inventory(inventory),
      taskManager(inventory)
{
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Initializes the Backpack system, preparing it for operation.
// Sets the initial state of the Backpack to IDLE.
void Backpack::begin()
{
    state = BackpackState::IDLE;
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Returns the current state of the Backpack.
BackpackState Backpack::getState() const
{
    return state;
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Registers a task with the backpacks associated TaskManager
// Returns true if the task registers sucessfully
bool Backpack::registerTask(const Task& task)
{
    return taskManager.registerTask(task);
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Start a task of the specified type using the TaskManager.
// Returns true if the task was successfully started, false otherwise.
bool Backpack::startTask(TaskType type)
{

    // If the backpack is not in the IDLE state, we cannot start a new task.
    if (state != BackpackState::IDLE)
    {
        return false;
    }

    // Attempt to start the task with the specified type.
    if (!taskManager.startTask(type))
    {
        // If the task could not be started 
        // (e.g., it is not registered, or another task is active), return false.
        return false;
    }
    else 
    {
    // Generate Event : Task started.
    BackpackEvent event{};

    event.type = EventType::TaskStarted;
    event.item = ItemType::Unknown;
    event.task = type;

    eventGenerator.emit(event);

    state = BackpackState::CHECKING_INVENTORY;

    // After starting the task, immediately check the inventory.
    // If the task is complete, the state will be updated to TASK_REMINDER;
    // otherwise, it will be updated to ACQUIRING_ITEMS.
    checkInventory();
    
    return true;

    }
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Stop the currently active task using the TaskManager.
// Resets the Backpack state to IDLE.
void Backpack::stopTask()
{
    BackpackEvent event{};

    event.type = EventType::TaskStopped;
    event.item = ItemType::Unknown;
    event.task = taskManager.getCurrentTask();

    eventGenerator.emit(event);

    taskManager.stopTask();
    state = BackpackState::IDLE;  
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Checks the inventory to determine if the current task is complete or 
// if items are still needed.
// Updates the Backpack state accordingly.
void Backpack::checkInventory()
{
    if (taskManager.isTaskComplete())
    {
        // Switch to user reminder state if the task is complete.
        BackpackEvent event{};

        event.type = EventType::TaskComplete;
        event.item = ItemType::Unknown;
        event.task = taskManager.getCurrentTask();

        eventGenerator.emit(event);

        state = BackpackState::TASK_REMINDER;

        event.type = EventType::TaskReminder;
        event.item = ItemType::Unknown;
        event.task = taskManager.getCurrentTask();

        eventGenerator.emit(event);

    }
    else
    {
        state = BackpackState::ACQUIRING_ITEMS;
        
        // Generate event : Item Required.
        BackpackEvent event{};

        event.type = EventType::ItemRequired;
        event.item = taskManager.getNextRequiredItem();
        event.task = taskManager.getCurrentTask();

        eventGenerator.emit(event);
    }
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Add item to the Backpack's inventory when it is scanned.
// This function should be called when an item is scanned into the backpack.
// Takes in the tagID (e.g. RFID Tag = 0x1234) 
void Backpack::itemAdded(uint32_t tagID)
{
    // Inventory updates regardless of backpack state.
    // (ie. user can add waterbottle without having to start a task.)
    inventory.addItem(tagID);

    ItemType itemType = inventory.getItemType(tagID);

    if (state == BackpackState::ACQUIRING_ITEMS)
    {
        if (!taskManager.isItemRequired(itemType))
        {
            BackpackEvent event{};
        
            event.type = EventType::ItemNotRequired;
            event.item = itemType;
            event.task = taskManager.getCurrentTask();
        
            eventGenerator.emit(event);
        }
        else
        {

        BackpackEvent event{};
        
        event.type = EventType::ItemAcquired;
        event.item = itemType;
        event.task = taskManager.getCurrentTask();
    
        eventGenerator.emit(event);
        }

        // Transition only if the task is complete and a task is running.
        checkInventory();
    }
    else 
    {
    // Item added but no tasks are active so simply add to backpack
    BackpackEvent event{};
        
    event.type = EventType::ItemAdded;
    event.item = itemType;
    event.task = taskManager.getCurrentTask();

    eventGenerator.emit(event);
    }
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Remove item from the backpack (sets this item location flag = outside)
void Backpack::itemRemoved(uint32_t tagID)
{   
    // Cannot remove an item that isn't in backpack
    if(inventory.removeItem(tagID))
    {
        ItemType itemType = inventory.getItemType(tagID);
        // NOTE: Add a checkInvetory function if the backpack should return to 
        // item aquisition if one is removed during a complete task.
        BackpackEvent event{};

        event.type = EventType::ItemRemoved;
        event.item = itemType;
        event.task = taskManager.getCurrentTask();

        eventGenerator.emit(event);
    }
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Picks up that an item was scanned but not necessarily placed into/out of the 
// backpack. Currently does nothing.
void Backpack::itemScanned(uint32_t tagID)
{
    // RFID/input subsystem integration point.
    // A scan does not automatically mean the item was added.
    // Calls either itemAdded or itemRemoved or perhaps also itemRegister.
    BackpackEvent event{};

    event.type = EventType::UnknownRFID;
    event.item = ItemType::Unknown;
    event.task = taskManager.getCurrentTask();

    eventGenerator.emit(event);
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Get the current active task if any
// Helper function, returns the current task type
TaskType Backpack::getCurrentTask() const
{
    return taskManager.getCurrentTask();
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Get the next required item for the currently active task
// Helper function, returns the current item type
ItemType Backpack::getNextRequiredItem() const
{
    return taskManager.getNextRequiredItem();
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Check if a task is currently active.
// Returns true if yes.
bool Backpack::isTaskActive() const
{
    return state != BackpackState::IDLE;
    // Could also implament by calling the TaskManager::isTaskActive()
    // return taskManager.isTaskActive();
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Check if the current task has all necessary items and is considered complete
// Returns true if complete
bool Backpack::isTaskComplete() const
{
    return taskManager.isTaskComplete();
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Task manager query if an item type is required for the current active task
bool Backpack::isItemRequired(ItemType type) const
{
    return taskManager.isItemRequired(type);
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Check if there is an event ready
bool Backpack::hasEvent() const
{
    return eventGenerator.hasEvent();
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Retrieve the last event generated by the FSM
BackpackEvent Backpack::getEvent()
{
    return eventGenerator.getEvent();
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Clears the events currenlty in the genertor. 
void Backpack::clearEvents()
{
    eventGenerator.clear();
}
// +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++